CREATE DATABASE MealSharing;
SET NAMES utf8mb4;
USE MealSharing;

CREATE  TABLE meal (
id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
location VARCHAR(255) NOT NULL,
`when` DATETIME NOT NULL,
max_reservations INT(10),
price DECIMAL NOT NULL,
created_date DATE NOT NULL
);

CREATE TABLE reservation(
id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
number_of_guests INT(10) UNSIGNED NOT NULL,
meal_id INT UNSIGNED NOT NULL,
created_date DATE NOT NULL
);